services:
  - type: web
    name: notei
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    healthCheckPath: /

